<a href="https://colab.research.google.com/github/harshattri52/NumPy-Python/blob/main/Numpy_june_2023.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

x=np.array([1,2,3,4])
print(x)
print(type(x))

[1 2 3 4]
<class 'numpy.ndarray'>


In [ ]:
y=[1,2,3,4]
print(y)
print(type(y))

[1, 2, 3, 4]
<class 'list'>


In [ ]:
%timeit [j**4 for j in range(1,9)]

2.58 µs ± 131 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)


In [ ]:
import numpy as np
%timeit np.arange(1,9)**4

2.24 µs ± 81.8 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)


In [ ]:
#ARRAYS

import numpy as np
x=[1,2,3,4]

y=np.array([1,2,3,4,5])
print(y)
print(type(y))
print(y.ndim) #ndim tells the dimension of an array

[1 2 3 4 5]
<class 'numpy.ndarray'>
1


In [ ]:
l=[]

for i in range(1,5):
  int_1=int(input("enter :"))
  l.append(int_1)

print(np.array(l))

enter :12
enter :13
enter :14
enter :15
[12 13 14 15]


In [ ]:
 arr2=np.array([[1,2,3,4],[4,3,2,1]])
 print(arr2)
 print(arr2.ndim)

[[1 2 3 4]
 [4 3 2 1]]
2


In [ ]:
 arr3=np.array([[1,2,3,4],[4,3,2,1],[1,2,3,4]])
 print(arr3)
 print(arr3.ndim)

[[1 2 3 4]
 [4 3 2 1]
 [1 2 3 4]]
2


In [ ]:
arn=np.array([1,2,3,4],ndmin=10)
print(arn)
print(arn.ndim)

[[[[[[[[[[1 2 3 4]]]]]]]]]]
10


In [ ]:
#L4
#zeroes
import numpy as np

ar_zero=np.zeros(4)
ar_zero1=np.zeros((3,4))

print(ar_zero)
print()
print(ar_zero1)


[0. 0. 0. 0.]

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [ ]:
#ones
ar_one = np.ones(4)

print(ar_one)

[1. 1. 1. 1.]


In [ ]:
#empty array
ar_emp=np.empty(4)

print(ar_emp)

[1. 1. 1. 1.]


In [ ]:
#range
arr_rn = np.arange(4)
print(arr_rn)

[0 1 2 3]


In [ ]:
#diagonal
ar_dia=np.eye(3)
print(ar_dia)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [ ]:
ar_dia=np.eye(3,5)
print(ar_dia)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]]


In [ ]:
#linespace
ar_lin=np.linspace(0,20,num=5)
print(ar_lin)

[ 0.  5. 10. 15. 20.]


In [ ]:
#L5
#RANDOM
#rand()---print ranom values between 0 and 1
import numpy as np

var=np.random.rand(4)

print(var)
print()

#for 2d array
var1=np.random.rand(4,4)
print(var1)

[0.05455815 0.35780627 0.84169605 0.29707819]

[[0.27568117 0.55173566 0.52148747 0.66922221]
 [0.50389677 0.29056211 0.66545872 0.86850951]
 [0.10784028 0.73818287 0.88276545 0.27859649]
 [0.00466365 0.80546861 0.98866684 0.96680014]]


In [ ]:
#randn()--print values close to zero

var2=np.random.randn(5)

print(var2)

[ 0.51776588 -0.05502715 -0.3616607  -1.20455581  1.88559139]


In [ ]:
#ranf()--
var3=np.random.ranf(4)

print(var3)

[0.24520766 0.5492878  0.85700301 0.19332257]


In [ ]:
#randint--
var3=np.random.ranf(4)

print(var3)

[0.06367646 0.73001002 0.65035448 0.29209577]


In [ ]:
#randint()
#var4=np.random.randint(min,max,total_values)
var4=np.random.randint(5,20,5)

print(var4)

[16 12 15 11  7]


In [ ]:
#L6
#DATA TYPE
import numpy as np

var=np.array([1,2,3,4])

print("Data Type :",var.dtype)

Data Type : int64


In [ ]:
var=np.array([1.0,1.2,1.3])

print("Data Type :",var.dtype)

Data Type : float64


In [ ]:
var=np.array(["A","S","D","F"])

print("Data Type :",var.dtype)

Data Type : <U1


In [ ]:
var=np.array([1,2,3,4,"a","b"])

print("Data Type :",var.dtype)

Data Type : <U21


In [ ]:
x = np.array([1,2,3,4],dtype=np.int8)

print("Data Type : ",x.dtype)

Data Type :  int8


In [ ]:
x1 = np.array([1,2,3,4],dtype= "f")

print("Data Type : ",x1.dtype)
print(x1)

Data Type :  float32
[1. 2. 3. 4.]


In [ ]:
#converting data types to different data types
x2 = np.array([1,2,3,4])

new=np.float32(x2)

new_one=np.int_(new)
print("Data Type : ",x2.dtype)
print("Data Type : ",new.dtype)
print("Data Type : ",new_one.dtype)
print(x2)
print(new)
print(new_one)

Data Type :  int64
Data Type :  float32
Data Type :  int64
[1 2 3 4]
[1. 2. 3. 4.]
[1 2 3 4]


In [ ]:
x3 = np.array([1,2,3,4])

new_1=x3.astype(float)

print(x3)
print(new_1)

[1 2 3 4]
[1. 2. 3. 4.]


In [ ]:
#L7
#ARITHMETIC OPERATION
import numpy as np

var=np.array([1,2,3,4])
varadd=var+3
print(varadd)

[4 5 6 7]


In [ ]:
var1=np.array([1,2,3,4])
var2=np.array([1,2,3,4])
varadd=var1+var2
print(varadd)

[2 4 6 8]


In [ ]:
#byfunction
var1=np.array([1,2,3,4])
var2=np.array([1,2,3,4])
varadd=np.add(var1,var2)
print(varadd)


[2 4 6 8]


In [ ]:
#2D ARRAY
var1=np.array([[1,2,3,4],[1,2,3,4]])
var2=np.array([[1,2,3,4],[1,2,3,4]])
varadd=np.add(var1,var2)
print(varadd)

[[2 4 6 8]
 [2 4 6 8]]


In [ ]:
#reciprocal
var=np.array([1,2,3,4])
rec=np.reciprocal(var)
print(rec)

[1 0 0 0]


In [ ]:
#L8
#Arithmetic FUNCTIONS
import numpy as np

var=np.array([4,4,1,2,34,5,6,7])

print("min :",np.min(var),np.argmin(var))
print("max :",np.max(var),np.argmax(var))

min : 1 2
max : 34 4


In [ ]:
var=np.array([4,4,5,6,7])

print(np.cumsum(var))

[ 4  8 13 19 26]


In [ ]:
#L9
#SHAPE
import numpy as np
var = np.array([[1,2],[1,2]])

print(var)
print()
print(var.shape)

[[1 2]
 [1 2]]

(2, 2)


In [ ]:
#reshape
import numpy as np
var2=np.array([1,2,3,4,5,6])
print(var2)
print(var2.ndim)

print()
x=var2.reshape(3,2)

print(x)
print(x.ndim)

[1 2 3 4 5 6]
1

[[1 2]
 [3 4]
 [5 6]]
2


In [ ]:
#L10
#broadcasting
import numpy as np

var1=np.array([1,2,3])

var2=np.array([1,2,3])

print(var1+var2)

[2 4 6]


In [ ]:
#L11
 #indexing
import numpy as np

var1=np.array([1,2,3]) #1d array

print(var1[2])

var2=np.array([[1,2,3],[4,5,6]]) #2d array

print(var2[1,2])

var3=np.array([[[1,2,3],[4,5,6],[7,8,9]]]) #3d array

print(var3[0,2,0])

3
6
7


In [ ]:
#slicing
import numpy as np

var1=np.array([1,2,3,4,5,6])

print(var1)

print()

print(var1[1:4])
print(var1[:4])
print(var1[1:])
print(var1[::2])

[1 2 3 4 5 6]

[2 3 4]
[1 2 3 4]
[2 3 4 5 6]
[1 3 5]


In [ ]:
#L12
#Iteration
import numpy as np

var=np.array([1,2,3,4,5,6])

print(var)
print()
for i in var:
  print(i)



[1 2 3 4 5 6]

1
2
3
4
5
6


In [ ]:
var2=np.array([[1,2,3],[4,5,6]]) #2d array

print(var2)
print()
for j in var2:
  print(j)

#for 2d in a line
for k in var2:
  for l in k:
    print(l)

[[1 2 3]
 [4 5 6]]

[1 2 3]
[4 5 6]
1
2
3
4
5
6
